### ISSUE TITLE
[bug]: run dekstop failed on windows system

### ISSUE THREAD

**Issue by yamasite** [netless-io/flat#1031]
## Environment

Windows 10

## Steps to reproduce

After executing `yarn run start`.

The following error occurs:

```shell
C:\Users\WL\Documents\GitHub\flat\node_modules\electron\dist\electron.exe exited with signal SIGINT

(node:1656) ExtensionLoadWarning: Warnings loading extension at C:\Users\WL\AppData\Roaming\Electron\extensions\fmkadmapgofadopljbjfkapdkoienihi: Unrecognized manifest key 'browser_action'. Unrecognized manifest key 'minimum_chrome_version'. Unrecognized manifest key 'update_url'. Cannot load extension with file or directory name _metadata. Filenames starting with "_" are reserved for use by the system.

Checking for update
Update for version 11.3.0 is not available (latest version: 1.1.0-beta.1, downgrade is disallowed).

Checking for update
Update for version 11.3.0 is not available (latest version: 1.1.0, downgrade is disallowed).
```

The app launches successfully with errors and I can neither create nor join a room:

![image](https://user-images.githubusercontent.com/10089260/138380457-93845940-a91d-4046-91dd-b4bccc3135ad.png)

**Comment by BlackHole1** [comment]
this is a known problem, but one that we currently do not have the ability to solve. We can only wait for `agora-electron-sdk` to fix it

the root cause is: on windows, you have to use 32-bit nodejs. One temporary solution is to switch your nodejs to 32-bit and re-execute `yarn run bootstrap`

Related Discussions: https://github.com/netless-io/flat/issues/996#issuecomment-943208480

**Comment by BlackHole1** [comment]
By the way, this warning does not have any side effects:


`(node:1656) ExtensionLoadWarning: Warnings loading extension at C:\Users\WL\AppData\Roaming\Electron\extensions\fmkadmapgofadopljbjfkapdkoienihi: Unrecognized manifest key 'browser_action'. Unrecognized manifest key 'minimum_chrome_version'. Unrecognized manifest key 'update_url'. Cannot load extension with file or directory name _metadata. Filenames starting with "_" are reserved for use by the system.`

This warning is because electron does not properly handle the formatting of chrome plugins. Please rest assured that it will not have any effect in itself. This issue is fixed in electron v16.x.x version. We will upgrade electron in the future, and this warning will not exist then.

Related Discussions: https://github.com/electron/electron/pull/29695
