### ISSUE TITLE
[bug]: whiteboard text tool can not typing on mobile device

### ISSUE THREAD

**Issue by leosuoxxo** [netless-io/flat#1112]
I thought it should be popup the keyboard for me to input the text, but it doesn't

![Image from iOS](https://user-images.githubusercontent.com/24968893/142802144-748385c7-4245-4012-8a4f-a2086aca0bcc.jpg)

Reproduction steps
Click on whiteboard with text tool

Device
iPad 15.1、iPhone 14.8

Browser
chrome、safari

**Comment by BlackHole1** [comment]
@Moskize91

**Comment by BlackHole1** [comment]
There is currently no solution to this problem.
Because our text tool is not a true input element, the ipad cannot respond to its events.
There is currently no way to actively open the keyboard, as it is restricted by the system.

**But don't worry, flat (iPad/iOS) is in development and is expected to go live soon.**
