### ISSUE TITLE
[chore]: (flat-web) upgrade vite to newer version

### ISSUE THREAD

**Issue by hyrious** [netless-io/flat#1219]
### `creat.svg` becomes `create.svg` ?

If you look at the two files, you will find that their contents are exactly the same.

- flat-web/src/assets/image/creat.svg
- flat-components/src/components/HomePage/HomePageHeroButton/icons/create.svg

That's what happens: vite will copy assets to dist folder and place them at the same dir, the hash after the file basename is calculated from its [contents](https://github.com/vitejs/vite/blob/9c8fb04f936c80971138da81c5757c353cb7396e/packages/vite/src/node/plugins/asset.ts#L308). So we have two files with different basename but same hash.

Then, vite uses the hash to make a <samp>Map</samp> to hold these files. So one of them will be dropped depending on the order they arrived at the processing. Because the processing is totally async, the order is not guaranteed, so we _randomly_ see the file missing/renaming.

Having two image files with the same contents should be wrong.

### <samp>TypeError: _typeof3 is not a function</samp>

Having investigated how it failed (#1218), I came up with some guess:

If you look at the unminified code, you will find the `_typeof` function is from `@babel/runtime`, which is injected to some libraries like `antd` for their ES5 compatibilities. For some reason we are using some commonjs libraries, the code will be transformed by rollup like such:

```js
// original code
var _typeof = require("@babel/runtime/helpers/typeof")
console.log(_typeof("a"))
```
&darr; &darr; &darr;
```js
// rollup -p commonjs
import require$$0 from '@babel/runtime/helpers/typeof';
var _typeof = require$$0;
console.log(_typeof("a"));
```
&darr; &darr; &darr;
```js
// @babel/runtime/helpers/typeof is a commonjs module
// bundlers should wrap it with some interop
var require$$0 = wrapWithInterop(require_typeof_result)
// require$$0 = { default: _typeof }
var _typeof = require$$0;
console.log(_typeof("a")); // Err!
```

This will happen on all commonjs modules that are exporting a default function, i.e., `module.exports = function() {...}`.

Sadly there's no good solution to this situation, one thing we could do is not using this kind of commonjs libraries. I've found that we wrongly bundled the commonjs version antd because `@netless/tool-box`, `@netless/player-controller` are depending on it. (they are in commonjs, which has `require("antd")`).

**Comment by BlackHole1** [comment]
**Great!!!!**

> On the first point, I add a little extra information

Compare the two build tasks:
1. https://github.com/netless-io/flat/runs/4456824065?check_suite_focus=true#step:5:181
<img width="779" alt="图片" src="https://user-images.githubusercontent.com/8198408/146498676-71cea68b-0d05-40af-920d-cb3c51d34663.png">


2. https://github.com/netless-io/flat/runs/4456667325?check_suite_focus=true#step:5:185
<img width="720" alt="图片" src="https://user-images.githubusercontent.com/8198408/146498711-4d7102a5-cfc6-4630-b356-4d9d325c6f6d.png">

They are all built on the same piece of code, but the results are not the same

To do this, I wrote the `fuzzing docker image`, but it did not reproduce.
Because I changed the `create.svg` and `creat.svg` contents

<img width="2395" alt="图片" src="https://user-images.githubusercontent.com/8198408/146499015-431b26dd-0f3f-4ee9-9c0a-8194934dcd9a.png">

I have also looked at the source code of vite and you are right. Beause:

<img width="703" alt="图片" src="https://user-images.githubusercontent.com/8198408/146499351-66982f13-8fc7-4ece-b059-c17533436ff2.png">
