### ISSUE TITLE
[chore]: improve configure-agora-sdk.js

### ISSUE THREAD

**Issue by BlackHole1** [netless-io/flat#1444]
@crimx

_Originally posted by @BlackHole1 in https://github.com/netless-io/flat/pull/1442#discussion_r836016603_

**Comment by hyrious** [comment]
FYI, one of the purposes of configure-agora-sdk.js is updating the .npmrc file before `yarn install`, so that agora-electron-sdk will read correct values before it downloads the binary.

However, this behavior is not needed after using pnpm's [neverBuiltDependencies](https://pnpm.io/package_json#pnpmneverbuiltdependencies). The downloading work is totally handed to the main-app/postinstall script.

The `node-linker=hoisted` option was used to address some badly developped storybook plugins. But that will cause the other problem -- common dependencies in different versions will be hard to locate the correct version. In case you haven't seen it, the dependency `find-up` has 4 versions in our project:

```bash
> pnpm why -r find-up@2
devDependencies:
eslint-config-react-app 7.0.0
└─┬ eslint-plugin-import 2.25.4
  └─┬ eslint-module-utils 2.7.3
    └── find-up 2.1.0

> pnpm why -r find-up@3
...@storybook...
webpack 4.46.0
   ...
   find-up 3.0.0

> pnpm why -r find-up@4
@storybook/semver
└── find-up 4.1.0

> pnpm why -r find-up@5
@storybook/manager-webpack5 6.3.1
   ...
   find-up 5.0.0
```

So how could that option break things? It is because when you have multiple different versions of the same package, pnpm will create symlinks to different folders (all hoisted to the top), like such:

```bash
find-up // default version
find-up@4.1.0
...
some-package
  |- node_modules
       |- find-up ~> find-up@4.1.0
```

If some package's custom resolver (like vite) did not follow symlinks, it will find the wrong dependency, which may break things.
