### ISSUE TITLE
Is it possible to use "Agora Flat Open Source Virtual Classroom" within a Flutter application?

### ISSUE THREAD

**Issue by Zohalmohal** [netless-io/flat#1571]
I am just wondering to know if it is possible to integrate Agora Flat Open Source Virtual Classroom with Flutter? Is there any example/project doing this?

**Comment by BlackHole1** [comment]
CC: @aderan

**Comment by aderan** [comment]
@Zohalmohal Flat already has [Android version](https://github.com/netless-io/flat-android) and [iOS version](https://github.com/netless-io/flat-iOS), due to the development resource limitation, we will not develop Flutter version in the near future.
Flat currently uses [Agora RTC SDK](https://pub.dev/packages/agora_rtc_engine), [Agora RTM SDK](https://pub.dev/packages/agora_rtm), [Agora Whiteboard SDK ](https://pub.dev/packages/whiteboard_sdk_flutter) all have Flutter version. if it is a personal practice, you can compare the existing interface implementation.

**Comment by aderan** [comment]
@Zohalmohal  Now we have a flutter library quick access to Agora Whiteboard. It's Low-cost, Scenario-based, Configurable. It's open source at [fastboard_flutter source](https://github.com/netless-io/fastboard_flutter), pub at [fastboard_flutter pub address](https://pub.dev/packages/fastboard_flutter).
