### ISSUE TITLE
why is this js file so big？

### ISSUE THREAD

**Issue by shunyue1320** [netless-io/flat#1578]
why is this js file so big？
<img width="1499" alt="image" src="https://user-images.githubusercontent.com/47295879/174571655-f5bfb690-ae54-453e-9ad5-97d7145768a7.png">

**Comment by BlackHole1** [comment]
@hyrious

**Comment by hyrious** [comment]
Because we didn't configure the [`manualChunks`](https://vitejs.dev/guide/build.html#chunking-strategy) option in vite.config.ts. By default vite leaves it as empty (i.e. the same as rollup's default behavior). You can treat that as bundled all dependencies in node_modules. You can turn on the [visualizer](https://github.com/netless-io/flat/blob/76d93b0e9cdcf3c300ebcc5afdefd3324b41a4f6/desktop/renderer-app/vite.config.ts#L42-L48) plugin to know what modules it includes.

Manually configuring chunks can be hard because you don't know which dependencies are not going to update. It could easily become a false-optimization.

Below are some important libraries that Flat is depending on, which should give you the reason about the vendors size:

| package | [bundled size](https://bundlephobia.com) |
|---|---|
| agora-rtc-sdk-ng + agora-rtm-sdk | 1.1 MB + 0.5 MB |
| white-web-sdk | 2.3 MB |
| @netless/window-manager (video-js) | 1 MB |
| @netless/app-slide (pixi-js) | 1.6 MB |
| @netless/app-monaco (monaco-editor) | 0.3 MB |
| antd + @ant-design/icons | 1.2 MB + 0.7 MB |

**Comment by crimx** [comment]
Flat was created initially as an electron application which is filesize insensitive. We were focusing on product POC and tried to launch a workable product as fast as possible. After months of evolving we finally gained enough feedbacks from realworld tutors. The fundamental shap of Flat project I think has come to a level of stability.

Optimization is on the way and for a start, the giant refactoring PR that is merged yesterday splits the different functionalities into on-demand dynamic modules. This should improve the initial page load.
