### ISSUE TITLE
web有vue版吗？

### ISSUE THREAD

**Issue by Ken-LK** [netless-io/flat#1823]

**Comment by hyrious** [comment]
没有，也没有开发和维护的打算。
项目里使用的白板/音视频库都不依赖特定的前端框架，可以接入任何标准 web 环境。例如组件 fastboard 可以直接参考 [原生方式](https://github.com/netless-io/fastboard#vanilla-javascript) 接入。

- - -

No we don't plan to create & maintain another Flat with a different front-end framework.
You're free (any easy?) to create one by yourself since the core functions (whiteboard & web-rtc) in Flat does not rely on any front-end framework.

**Comment by Ken-LK** [comment]
多谢
