### ISSUE TITLE
error with Bluetooth

### ISSUE THREAD

**Issue by Yan1205** [netless-io/flat#2107]
When I connect Bluetooth, the audio still plays through the speakers on both the tablet and the phone instead of playing on the headphones.

**Comment by Yan1205** [comment]
REP-AN00
Xiaomi Pad 6
OnePlus Ace 2
Redmi K60 Pro
...

**Comment by hyrious** [comment]
By "audio" do you mean the media courseware (mp3, mp4, etc.) inserted in the room, or the voice from other's microphone?

The former does not handle speaker change event since it is not common to see a web audio player to provide this function. Actually Flat uses the library [plyr](https://github.com/sampotts/plyr) which does not provide a direct way to call [setSinkId](https://github.com/sampotts/plyr). So unfortunately we have no way to provide a way to switch the speaker of the media sourcewares. They will use the default speaker of the system (you can set the default device in your system level).

The later one switches speakers when new devices are connected, if you find this not working you can give use more details (like which OS and which device you're using) to help us reproduce it.
